#
# CMakeCM
# CMake Common Modules.
#
# SPDX-FileCopyrightText: 2024-2025 flagarde
#
# SPDX-License-Identifier: MIT
#
cmake_policy(VERSION ${CMAKE_VERSION})

include(SetupModulesList)

include(Missives)

# message and missive give error if called without argument
# FATAL_ERROR and SEND_ERROR are not tested here

message(STATUS "======= Test WARNING =========")
message(WARNING)
missive(WARNING)
message("WARNING")
missive("WARNING")
message(WARNING "")
missive(WARNING "")
message(WARNING "Te;st")
missive(WARNING "Te;${CMCM_FG_BLUE}st${CMCM_TO_DEFAULT}")
message(WARNING "Te;st" "Te;st")
missive(WARNING "Te;${CMCM_FG_BLUE}st${CMCM_TO_DEFAULT}" "Te;st")
message(STATUS "==============================\n")

message(STATUS "==== Test AUTHOR_WARNING =====")
message(AUTHOR_WARNING)
missive(AUTHOR_WARNING)
message("AUTHOR_WARNING")
missive("AUTHOR_WARNING")
message(AUTHOR_WARNING "")
missive(AUTHOR_WARNING "")
message(AUTHOR_WARNING "Te;st")
missive(AUTHOR_WARNING "Te;${CMCM_FG_BLUE}st${CMCM_TO_DEFAULT}")
message(AUTHOR_WARNING "Te;st" "Te;st")
missive(AUTHOR_WARNING "Te;${CMCM_FG_BLUE}st${CMCM_TO_DEFAULT}" "Te;st")
message(STATUS "==============================\n")

message(STATUS "==== Test DEPRECATION =====")
message(DEPRECATION)
missive(DEPRECATION)
message("DEPRECATION")
missive("DEPRECATION")
message(DEPRECATION "")
missive(DEPRECATION "")
message(DEPRECATION "Te;st")
missive(DEPRECATION "Te;${CMCM_FG_BLUE}st${CMCM_TO_DEFAULT}")
message(DEPRECATION "Te;st" "Te;st")
missive(DEPRECATION "Te;${CMCM_FG_BLUE}st${CMCM_TO_DEFAULT}" "Te;st")
message(STATUS "==============================\n")

message(STATUS "==== Test =====")
message("")
missive("")
message("Te;st")
missive("Te;${CMCM_FG_BLUE}st${CMCM_TO_DEFAULT}")
message("Te;st" "Te;st")
missive("Te;${CMCM_FG_BLUE}st${CMCM_TO_DEFAULT}" "Te;st")
message(STATUS "==============================\n")

message(STATUS "==== Test STATUS =====")
message(STATUS)
missive(STATUS)
message("STATUS")
missive("STATUS")
message(STATUS "")
missive(STATUS "")
message(STATUS "Te;st")
missive(STATUS "Te;${CMCM_FG_BLUE}st${CMCM_TO_DEFAULT}")
message(STATUS "Te;st" "Te;st")
missive(STATUS "Te;${CMCM_FG_BLUE}st${CMCM_TO_DEFAULT}" "Te;st")
message(STATUS "==============================\n")

if("${CMAKE_VERSION}" VERSION_GREATER "3.14.7")

message(STATUS "==== Test NOTICE =====")
message(NOTICE)
missive(NOTICE)
message("NOTICE")
missive("NOTICE")
message(NOTICE "")
missive(NOTICE "")
message(NOTICE "Te;st")
missive(NOTICE "Te;${CMCM_FG_BLUE}st${CMCM_TO_DEFAULT}")
message(NOTICE "Te;st" "Te;st")
missive(NOTICE "Te;${CMCM_FG_BLUE}st${CMCM_TO_DEFAULT}" "Te;st")
message(STATUS "==============================\n")

message(STATUS "==== Test VERBOSE =====")
message(VERBOSE)
missive(VERBOSE)
message("VERBOSE")
missive("VERBOSE")
message(VERBOSE "")
missive(VERBOSE "")
message(VERBOSE "Te;st")
missive(VERBOSE "Te;${CMCM_FG_BLUE}st${CMCM_TO_DEFAULT}")
message(VERBOSE "Te;st" "Te;st")
missive(VERBOSE "Te;${CMCM_FG_BLUE}st${CMCM_TO_DEFAULT}" "Te;st")
message(STATUS "==============================\n")

message(STATUS "==== Test DEBUG =====")
message(DEBUG)
missive(DEBUG)
message("DEBUG")
missive("DEBUG")
message(DEBUG "")
missive(DEBUG "")
message(DEBUG "Te;st" "To;to;")
missive(DEBUG "Te;${CMCM_FG_BLUE}st${CMCM_TO_DEFAULT}" "To;to;")
message(DEBUG "Te;st" "Te;st" "To;to;")
missive(DEBUG "Te;${CMCM_FG_BLUE}st${CMCM_TO_DEFAULT}" "Te;st" "To;to;")
message(STATUS "=====================\n")

message(STATUS "==== Test TRACE =====")
message(TRACE)
missive(TRACE)
message("TRACE")
missive("TRACE")
message(TRACE "")
missive(TRACE "")
message(TRACE "Te;st")
missive(TRACE "Te;${CMCM_FG_BLUE}st${CMCM_TO_DEFAULT}")
message(TRACE "Te;st" "Te;st")
missive(TRACE "Te;${CMCM_FG_BLUE}st${CMCM_TO_DEFAULT}" "Te;st")
message(STATUS "=====================\n")

endif()

missive_type(NAME "ERROR" STYLE "CMCM::FG::BOLD::RED" APPEND_BEGIN "!! " APPEND_END " !!" APPEND_STYLE "CMCM::FG::BOLD::RED")
missive_type(NAME "WARN" STYLE "CMCM::FG::BOLD::YELLOW" APPEND_BEGIN "## " APPEND_END " ##" APPEND_STYLE "CMCM::FG::BOLD::YELLOW")
missive_type(NAME "INFO" STYLE "CMCM::FG::BOLD::GREEN" APPEND_BEGIN "** " APPEND_END " **" APPEND_STYLE "CMCM::FG::BOLD::GREEN")
missive_type(NAME "NOTE" STYLE "CMCM::FG::BOLD::MAGENTA" APPEND_BEGIN "-- " APPEND_END " --" APPEND_STYLE "CMCM::FG::BOLD::MAGENTA")
missive_type(NAME "TO_REMOVE" PARENT_SCOPE "DEBUG" APPEND_BEGIN "-- " APPEND_END " --" APPEND_STYLE "CMCM::FG::RED" STYLE "CMCM::FG::RED")
missive_type(NAME "TO_ADD" PARENT_SCOPE "DEBUG" APPEND_BEGIN "++ " APPEND_END " ++" APPEND_STYLE "CMCM::FG::GREEN" STYLE "CMCM::FG::GREEN")

missive(ERROR "ERROR")
missive(WARN "WARN ${CMCM_FG_BLUE}BLUE${CMCM_TO_DEFAULT} YELLOW AGAIN")
missive(INFO "INFO")
missive(NOTE "NOTE")
missive(TO_REMOVE "TO_REMOVE")
missive(TO_ADD "TO_ADD")
