---
name: windows

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: CMake v${{ matrix.cmake_version }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        cmake_version:
          - '3.0'
          - '3.1'
          - '3.2'
          - '3.3'
          - '3.4'
          - '3.5'
          - '3.6'
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
          - '3.14'
          - '3.15'
          - '3.16'
          - '3.17'
          - '3.18'
          - '3.19'
          - '3.20'
          - '3.21'
          - '3.22'
          - '3.23'
          - '3.24'
          - '3.25'
          - '3.26'
          - '3.27'
          - '3.28'
          - '3.29'
          - '3.30'
          - '3.31'
          - '4.0'

    steps:

    - name: 📥 Checkout
      uses: actions/checkout@v4
    - name: 📂 Load .env file
      if: hashFiles('.github/workflows/env/.env') != ''
      uses: xom9ikk/dotenv@v2
      with:
        path: .github/workflows/env
    - name: Check .env.${{ github.workflow }} file existence
      id: check_file
      uses: andstor/file-existence-action@v3
      with:
        files: .github/workflows/env/.env.${{ github.workflow }}
    - name: 📂 Load .env.${{ github.workflow }} file
      if: steps.check_file.outputs.files_exists == 'true'
      uses: xom9ikk/dotenv@v2
      with:
        path: .github/workflows/env
        mode: ${{ github.workflow }}

    - name: ⬇️ Setup Visual Studio
      uses: ilammy/msvc-dev-cmd@v1.13.0

    - name: ⬇️ Setup CMake
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: ~3.${{ matrix.cmake_version }}
        ninjaVersion: ^1.11.1

    - name: 🔧 Generate with v3.${{ matrix.cmake_version }}
      if: ${{ matrix.cmake_version < 13 }}
      run: cmake -E make_directory ${{ env.CMAKE_BINARY_PREFIX }}; cmake -E chdir ${{ env.CMAKE_BINARY_PREFIX }} cmake -G "Ninja" -Werror=dev -Werror=deprecated -DCMAKE_BUILD_TYPE=${{ env.CMAKE_BUILD_TYPE }} -DBUILD_DOCS=${{ env.BUILD_DOCS }} ${{ github.workspace
        }}/${{ env.CMAKE_SOURCE_PREFIX}}

    - name: 🔧 Generate with v3.${{ matrix.cmake_version }}
      if: ${{ matrix.cmake_version >= 13 &&  matrix.cmake_version < 17 }}
      run: cmake -S ${{ env.CMAKE_SOURCE_PREFIX }} -B ${{ env.CMAKE_BINARY_PREFIX }} -G "Ninja" -Werror=dev -Werror=deprecated -DCMAKE_BUILD_TYPE=${{ env.CMAKE_BUILD_TYPE }} -DBUILD_DOCS=${{ env.BUILD_DOCS }}

    - name: 🔧 Generate with v3.${{ matrix.cmake_version }}
      if: ${{ matrix.cmake_version >= 17 }}
      run: cmake -S ${{ env.CMAKE_SOURCE_PREFIX }} -B ${{ env.CMAKE_BINARY_PREFIX }} -G "Ninja Multi-Config" -Werror=dev -Werror=deprecated -DBUILD_DOCS=${{ env.BUILD_DOCS }}

    - name: 🧪 Test
      run: ctest -C ${{ env.CMAKE_BUILD_TYPE }} -VV --output-on-failure
      working-directory: ${{ env.CMAKE_BINARY_PREFIX }}
